package app

import (
	"github.com/tvanriel/cloudsdk/http"
	"github.com/tvanriel/cloudsdk/kubernetes"
	"github.com/tvanriel/cloudsdk/logging"
	"github.com/tvanriel/cloudsdk/mysql"
	"github.com/tvanriel/cloudsdk/prometheus"
	"github.com/tvanriel/cloudsdk/redis"
	"github.com/tvanriel/cloudsdk/s3"
	"github.com/tvanriel/ps-bot-2/internal/commands"
	"github.com/tvanriel/ps-bot-2/internal/config"
	"github.com/tvanriel/ps-bot-2/internal/discord"
	"github.com/tvanriel/ps-bot-2/internal/metrics"
	"github.com/tvanriel/ps-bot-2/internal/player"
	"github.com/tvanriel/ps-bot-2/internal/queues"
	"github.com/tvanriel/ps-bot-2/internal/repositories"
	"github.com/tvanriel/ps-bot-2/internal/saver"
	"github.com/tvanriel/ps-bot-2/internal/soundstore"
	"github.com/tvanriel/ps-bot-2/internal/web"
	"go.uber.org/fx"
)

func DiscordBot() {
	fx.New(
		fx.Provide(
			config.ViperConfiguration,
			config.MySQLConfiguration,
			config.DiscordConfiguration,
			config.LoggingConfiguration,
                        config.PrometheusConfiguration,
			config.StorageConfiguration,
			config.S3Configuration,
			config.KubernetesConfiguration,
			config.SaverConfiguration,
			config.RedisConfiguration,
		),
		logging.FXLogger(),
		mysql.Module,
		logging.Module,
		player.Module,
		discord.Module,
		repositories.Module,
		commands.Module,
                prometheus.Module,
		soundstore.Module,
		s3.Module,
		saver.Module,
		kubernetes.Module,
		redis.Module,
		queues.Module,
                metrics.Module,
	).Run()
}

func Web() {
	fx.New(
		fx.Provide(
			config.ViperConfiguration,
			config.MySQLConfiguration,
			config.HttpConfiguration,
			config.RedisConfiguration,
			config.LoggingConfiguration,
			config.S3Configuration,
			config.StorageConfiguration,
                        config.PrometheusConfiguration,
		),
		logging.FXLogger(),
		mysql.Module,
		http.Module,
		web.Module,
		redis.Module,
		logging.Module,
		repositories.Module,
		soundstore.Module,
                prometheus.Module,
		queues.Module,
		s3.Module,
	).Run()
}
